# Site settings | 网站设置
title: songtingting
SEOTitle: songtingting的博客
header-img: img/home-bg-he.png
email: 1498830837@qq.com
description: "songtingting的博客"
keyword: "songtingting的博客, songtingting blog"
url: "http://bigfish-qq.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/bigfish-qq/bigfish-qq.github.io.git" #code repository | 代码仓库


# Sidebar settings | 侧边栏设置
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "生命是一个播种的季节!"
sidebar-avatar: /img/head_1.jpeg      # 头像





# SNS settings | 社交网络设置
facebook_username: rainbom.z
github_username: bigfish-qq
zhihu_username: 大鱼
csdn_username: qq_38013013




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
# 转换时排除某些文件夹或文件。被排除的文件或文件夹的路径是相对于网站源码目录的，源码目录以外不受影响。
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`

Regeneration: true    # 允许文件修改时自动重新生成网站。





# Gems
# from PR#40, to support local preview for Jekyll 3.0
plugins: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important

# Gitalk
gitalk:
  enable: true    # 是否开启Gitalk评论
  clientID: 0fa8d9e1e8fb24f30eaf                            #生成的clientID
  clientSecret: 9d4a72c8ec676f9113ecbbc1303aca5446089c45    #生成的clientSecret
  repo: bigfish-qq.github.io    #仓库名称
  owner: bigfish-qq    # github用户名
  admin: bigfish-qq
  distractionFreeMode: true # 是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: 9acee03023ad0c6c993dd86df81e2ac8


# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 0              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "GitHub·bigfish-qq",
        href: "http://bigfish-qq.github.io"
    },{
        title: "CSDN·何处是归途",
        href: "https://blog.csdn.net/qq_38013013"
    },{
        title: "知乎·大鱼",
        href: "https://www.zhihu.com/people/da-yu-59-73"
    },{
        title: "GitBook·bigfish-qq",
        href: "http://bigfish-qq.github.io"
    }
]
